binfmt_elf: Fix build
Conflict with this commit from Sultan: https://github.com/Pzqqt/android_kernel_xiaomi_whyred/commit/dad94410e0ba7b64cdc132a441bf0b2f7d115010

../fs/binfmt_elf.c:1101:10: error: member reference type 'struct (anonymous struct at ../fs/binfmt_elf.c:686:2)' is not a pointer; did you mean to use '.'?
                    loc->elf_ex.e_type == ET_DYN && !interpreter)
                    ~~~^~
                       .
1 error generated.

Signed-off-by: sohamxda7 <sensoham135@gmail.com>